export const board = [
  [
    { value: 'A8', x: 1, y: 8 },
    {
      value: 'B8',
      x: 2,
      y: 8,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'C8', x: 3, y: 8 },
    {
      value: 'D8',
      x: 4,
      y: 8,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'E8', x: 5, y: 8 },
    {
      value: 'F8',
      x: 6,
      y: 8,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'G8', x: 7, y: 8 },
    {
      value: 'H8',
      x: 8,
      y: 8,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
  ],
  [
    {
      value: 'A7',
      x: 1,
      y: 7,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'B7', x: 2, y: 7 },
    {
      value: 'C7',
      x: 3,
      y: 7,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'D7', x: 4, y: 7 },
    {
      value: 'E7',
      x: 5,
      y: 7,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'F7', x: 6, y: 7 },
    {
      value: 'G7',
      x: 7,
      y: 7,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'H7', x: 8, y: 7 },
  ],
  [
    { value: 'A6', x: 1, y: 6 },
    {
      value: 'B6',
      x: 2,
      y: 6,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'C6', x: 3, y: 6 },
    {
      value: 'D6',
      x: 4,
      y: 6,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'E6', x: 5, y: 6 },
    {
      value: 'F6',
      x: 6,
      y: 6,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'G6', x: 7, y: 6 },
    {
      value: 'H6',
      x: 8,
      y: 6,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
  ],
  [
    {
      value: 'A5',
      x: 1,
      y: 5,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'B5', x: 2, y: 5 },
    {
      value: 'C5',
      x: 3,
      y: 5,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'D5', x: 4, y: 5 },
    {
      value: 'E5',
      x: 5,
      y: 5,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'F5', x: 6, y: 5 },
    {
      value: 'G5',
      x: 7,
      y: 5,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'H5', x: 8, y: 5 },
  ],
  [
    { value: 'A4', x: 1, y: 4 },
    {
      value: 'B4',
      x: 2,
      y: 4,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'C4', x: 3, y: 4 },
    {
      value: 'D4',
      x: 4,
      y: 4,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'E4', x: 5, y: 4 },
    {
      value: 'F4',
      x: 6,
      y: 4,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'G4', x: 7, y: 4 },
    {
      value: 'H4',
      x: 8,
      y: 4,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
  ],
  [
    {
      value: 'A3',
      x: 1,
      y: 3,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'B3', x: 2, y: 3 },
    {
      value: 'C3',
      x: 3,
      y: 3,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'D3', x: 4, y: 3 },
    {
      value: 'E3',
      x: 5,
      y: 3,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'F3', x: 6, y: 3 },
    {
      value: 'G3',
      x: 7,
      y: 3,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'H3', x: 8, y: 3 },
  ],
  [
    { value: 'A2', x: 1, y: 2 },
    {
      value: 'B2',
      x: 2,
      y: 2,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'C2', x: 3, y: 2 },
    {
      value: 'D2',
      x: 4,
      y: 2,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'E2', x: 5, y: 2 },
    {
      value: 'F2',
      x: 6,
      y: 2,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'G2', x: 7, y: 2 },
    {
      value: 'H2',
      x: 8,
      y: 2,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
  ],
  [
    {
      value: 'A1',
      x: 1,
      y: 1,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'B1', x: 2, y: 1 },
    {
      value: 'C1',
      x: 3,
      y: 1,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'D1', x: 4, y: 1 },
    {
      value: 'E1',
      x: 5,
      y: 1,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'F1', x: 6, y: 1 },
    {
      value: 'G1',
      x: 7,
      y: 1,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'H1', x: 8, y: 1 },
  ],
];
export const newBoard = [
  [
    { value: 'A8', x: 1, y: 8 },
    {
      value: 'B8',
      x: 2,
      y: 8,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'C8', x: 3, y: 8 },
    {
      value: 'D8',
      x: 4,
      y: 8,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'E8', x: 5, y: 8 },
    {
      value: 'F8',
      x: 6,
      y: 8,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'G8', x: 7, y: 8 },
    {
      value: 'H8',
      x: 8,
      y: 8,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
  ],
  [
    {
      value: 'A7',
      x: 1,
      y: 7,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'B7', x: 2, y: 7 },
    {
      value: 'C7',
      x: 3,
      y: 7,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'D7', x: 4, y: 7 },
    {
      value: 'E7',
      x: 5,
      y: 7,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'F7', x: 6, y: 7 },
    {
      value: 'G7',
      x: 7,
      y: 7,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'H7', x: 8, y: 7 },
  ],
  [
    { value: 'A6', x: 1, y: 6 },
    {
      value: 'B6',
      x: 2,
      y: 6,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'C6', x: 3, y: 6 },
    {
      value: 'D6',
      x: 4,
      y: 6,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'E6', x: 5, y: 6 },
    {
      value: 'F6',
      x: 6,
      y: 6,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'G6', x: 7, y: 6 },
    {
      value: 'H6',
      x: 8,
      y: 6,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
  ],
  [
    {
      value: 'A5',
      x: 1,
      y: 5,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'B5', x: 2, y: 5 },
    {
      value: 'C5',
      x: 3,
      y: 5,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'D5', x: 4, y: 5 },
    {
      value: 'E5',
      x: 5,
      y: 5,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'F5', x: 6, y: 5 },
    {
      value: 'G5',
      x: 7,
      y: 5,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'H5', x: 8, y: 5 },
  ],
  [
    { value: 'A4', x: 1, y: 4 },
    {
      value: 'B4',
      x: 2,
      y: 4,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'C4', x: 3, y: 4 },
    {
      value: 'D4',
      x: 4,
      y: 4,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'E4', x: 5, y: 4 },
    {
      value: 'F4',
      x: 6,
      y: 4,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'G4', x: 7, y: 4 },
    {
      value: 'H4',
      x: 8,
      y: 4,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
  ],
  [
    {
      value: 'A3',
      x: 1,
      y: 3,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'B3', x: 2, y: 3 },
    {
      value: 'C3',
      x: 3,
      y: 3,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'D3', x: 4, y: 3 },
    {
      value: 'E3',
      x: 5,
      y: 3,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'F3', x: 6, y: 3 },
    {
      value: 'G3',
      x: 7,
      y: 3,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'H3', x: 8, y: 3 },
  ],
  [
    { value: 'A2', x: 1, y: 2 },
    {
      value: 'B2',
      x: 2,
      y: 2,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'C2', x: 3, y: 2 },
    {
      value: 'D2',
      x: 4,
      y: 2,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'E2', x: 5, y: 2 },
    {
      value: 'F2',
      x: 6,
      y: 2,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'G2', x: 7, y: 2 },
    {
      value: 'H2',
      x: 8,
      y: 2,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
  ],
  [
    {
      value: 'A1',
      x: 1,
      y: 1,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'B1', x: 2, y: 1 },
    {
      value: 'C1',
      x: 3,
      y: 1,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'D1', x: 4, y: 1 },
    {
      value: 'E1',
      x: 5,
      y: 1,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'F1', x: 6, y: 1 },
    {
      value: 'G1',
      x: 7,
      y: 1,
      item: null,
      color: 'rgb(0 0 0 / 58%)',
      text: '#000',
    },
    { value: 'H1', x: 8, y: 1 },
  ],
];

export const numbers = [8, 7, 6, 5, 4, 3, 2, 1];
export const alfabeth = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'];

export const wCheksers = [
  {
    q: false,
    id: 1,
    group: 'w',
    x: 1,
    y: 1,
  },
  { group: 'w', q: false, id: 2, x: 3, y: 1 },
  { group: 'w', q: false, id: 3, x: 5, y: 1 },
  { group: 'w', q: false, id: 4, x: 7, y: 1 },
  //
  { group: 'w', q: false, id: 5, x: 2, y: 2 },
  { group: 'w', q: false, id: 6, x: 4, y: 2 },
  { group: 'w', q: false, id: 7, x: 6, y: 2 },
  { group: 'w', q: false, id: 8, x: 8, y: 2 },
  //
  { group: 'w', q: false, id: 9, x: 1, y: 3 },
  { group: 'w', q: false, id: 10, x: 3, y: 3 },
  { group: 'w', q: true, id: 11, x: 5, y: 3 },
  { group: 'w', q: false, id: 12, x: 7, y: 3 },
];

export const bCheksers = [
  { group: 'b', q: false, id: 13, x: 8, y: 8 },
  { group: 'b', q: false, id: 14, x: 6, y: 8 },
  { group: 'b', q: false, id: 15, x: 4, y: 8 },
  { group: 'b', q: false, id: 16, x: 2, y: 8 },
  //
  { group: 'b', q: false, id: 17, x: 7, y: 7 },
  { group: 'b', q: false, id: 18, x: 5, y: 7 },
  { group: 'b', q: false, id: 19, x: 3, y: 7 },
  { group: 'b', q: false, id: 20, x: 1, y: 7 },
  //
  { group: 'b', q: false, id: 21, x: 8, y: 6 },
  { group: 'b', q: true, id: 22, x: 6, y: 6 },
  { group: 'b', q: true, id: 23, x: 4, y: 6 },
  { group: 'b', q: false, id: 24, x: 2, y: 6 },
];
